### ISSUE TITLE
ox not in module core

### ISSUE THREAD

**Issue by mitch-cl** [Byte-Labs-Studio/bl_bridge#17]
SCRIPT ERROR: @bl_bridge/init.lua:143: there is no ox on module core!, please make sure you configured your convars on cfg!

But in the documentation ox is an option for core.

**Comment by HazeWorksOnFiveMServer** [comment]
even if there is no support for ox as framework at the momnet they should add it

**Comment by Frowmza** [comment]
we will

**Comment by Frowmza** [comment]
Added!
