### ISSUE TITLE
Standalone

### ISSUE THREAD

**Issue by Speedfreak4013** [Byte-Labs-Studio/bl_bridge#26]
I have a server that is standalone and I can't get bl_bridge to run on standalone, then I get:
SCRIPT ERROR: @bl_bridge/imports/server.lua:5: No such export core in resource bl_bridge

**Comment by Frowmza** [comment]
what resource you trying to use beside bridge?

**Comment by Speedfreak4013** [comment]
ox_lib and mm_radio
the radio needs these two ressources

**Comment by Speedfreak4013** [comment]
![Screenshot 2024-10-20 195334](https://github.com/user-attachments/assets/4163aef5-f5a0-4565-a638-ff8127afdd42)

**Comment by Frowmza** [comment]
Usually if standalone, we don't wanna use bridge, so ask him if there is a toggle for standalone to disable usage of the bridge, bridge only if we had a framework
